---
title: "PLSR_Ash"
output: html_document
date: "2024-02-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load Reference data

```{r}

# spectraldata=read.csv("Raw_spectra-MIR.csv")
spec_trt <- readRDS("spec_trt_MIR.RDS")
spec_trt <- spec_trt[,-2] #removing the data for the first wavenumber since it's all NAN's


df_f_Ash_1 <- readRDS("df_f_Ash_1.RDS")

df.f <- df_f_Ash_1[, !colnames(df_f_Ash_1) %in% c("Temp_factor", "H_C_factor","Ash_factor","O_C_factor")]

threshold_na <- 0.85 #for a 70% cut-off

df.f<-
  df.f %>% select(where(~mean(is.na(.)) < threshold_na))

spectraldata.fin.fin<-spec_trt[is.element(spec_trt$SSN, df.f$SSN),] ## FUSI Still unclear what this is for. Changed to reference spec_trt
 
```

## PLSR by Ash 1

```{r}

#select only the common Biochar samples in spectral and wet chemie data based on the fact that this data is subsetted

df.f <- df_f_Ash_1[, !colnames(df_f_Ash_1) %in% c("Temp_factor", "H_C_factor","Ash_factor","O_C_factor")]


names(df.f)
slprptr<-names(df.f[-c(2:4)]) #FUSI EDIT: removing metadata columns

pred<-as.data.frame(spec_trt[,1])
colnames(pred)<-"SSN"

mdl.stats<-NULL#Model stats container

#FUSI EDIT: started at 3, instead of 2 because the first column in the char type
for(p in 23:length(slprptr)){

#Select properties to predict one at a time and remove NAs  
df.sel<-df.f %>% select(SSN, slprptr[p]) %>% na.omit


#Plot and print Biochar properties boxplots
boxplot(df.sel[,slprptr[p]], las=2, xlab = slprptr[p], ylab = "")
dir.create("Plots_Boxplots_PLSR_MIR_Ash1")
png(paste0(getwd(),"/Plots_Boxplots_PLSR_MIR_Ash1/",slprptr[p],".png"))
print(boxplot(df.sel[,slprptr[p]], las=2, xlab = slprptr[p], ylab = ""))
dev.off()

# #Split samples inside loop for variables with many NAs
# #Set splitting proportion for the calibration and validation data
set.seed(123)
pool=df.f[sample(nrow(df.sel), round(0.3*nrow(df.sel),0)), ]
pool<-pool[order(pool$SSN),]
poolid<-pool$SSN

#Get calibration and validation datasets
val_df<-pool
cal_df1 <-subset(df.sel, !(df.sel$SSN %in% val_df$SSN))

# threshold to exclude the extreme 5% values
#KARARI UPDATE; 95% loses too many samples, changed to 99% 

cal_df <-subset(cal_df1, cal_df1[,2]>quantile(cal_df1[,2], 0.01)&cal_df1[,2] <quantile(cal_df1[,2], 0.99))
val_df1 <-subset(df.sel, (df.sel$SSN %in% val_df$SSN))
val_df <-subset(val_df1, val_df1[,2]>quantile(val_df1[,2], 0.01)&val_df1[,2] <quantile(val_df1[,2], 0.99))
#FUSI EDIT: first chunk is initial code - for some reason wasn't actually orering the dataframe. second chunk is my edit
#renames the non-working version with suffice _or
val_df_or<-val_df[order(rownames(val_df)),]
cal_df_or<-cal_df[order(rownames(cal_df)),]

val_df<-setorder(val_df)
cal_df<-setorder(cal_df)

 # Check if val_df is empty
  if (nrow(val_df) > 0) { 

#Subset pre-treated spectra by available reference data
val_spec<-spec_trt[is.element(spec_trt$SSN, val_df$SSN),]
cal_spec<-spec_trt[is.element(spec_trt$SSN, cal_df$SSN),]
cal_spec<-cal_spec[order(cal_spec$SSN),]
val_spec<-val_spec[order(val_spec$SSN),]


#Get no of calibration and validation datasets
N_cal<-nrow(cal_spec)
N_val<-nrow(val_spec)

#Model data
Xcal.f=cal_spec[,-1]
Xval.f=val_spec[,-1]
dfcal.f=cal_df[,-1]
dfval.f=val_df[,-1]

###### PLSR SOC
maxc <- 10  ## number of max components
#FUSI EDIT: max was 25
pls.md <- plsr(dfcal.f ~ ., data = Xcal.f, ncomp=maxc, validation = "CV", segments = 10)#10-fold CV
#Each iteration of the cross-validation process involves training the model on 9 of the 10 segments and testing it on the remaining segment, repeating this process 10 times to ensure each segment is used as a test set once.

## plot RMSEP vs. number of components
plot(pls.md, "val", main=slprptr[p]) 

dir.create("Components_plots_PLSR_MIR_Ash1")
png(paste0(getwd(),"/Components_plots_PLSR_MIR_Ash1/",slprptr[p],".png"))
print(plot(pls.md, "val", main=slprptr[p]))
dev.off()

## no. components to use, the one with the smallest adj RMSEP value
RMSEP.obj<-RMSEP(pls.md)
str(RMSEP.obj)

RMSEP.obj$val[1:2,1,]
nc <- as.numeric(sub("comps", "", names(which.min(RMSEP.obj$val[1,1,2:dim(RMSEP.obj$val[1:2,1,])[2]]))))
nc

#Generate relevant model name
md.nm<-paste0("pls.md.", slprptr[p], ".nc", nc)

#Rename model with the looped Biochar property
assign(x = md.nm, value = get("pls.md", pos = .GlobalEnv), pos = .GlobalEnv)

## predict to validation dataset
pls.prd <- predict(pls.md, ncomp = nc, newdata = Xval.f)

## Return prediction statistics
val.stats=round(goof(dfval.f, pls.prd, type = "spec"),3)
val.stats<-bind_cols(Property=paste0(Property=slprptr[p],"_val"), Comps="", N=N_val, val.stats)
val.stats

## calibration statistics
pls.pc <- predict(pls.md, ncomp = nc, newdata = Xcal.f)

pls.cal=round(goof(dfcal.f, pls.pc, type = "spec"),3)
cal.stats<-bind_cols(Property=paste0(Property=slprptr[p],"_cal"), Comps=as.character(nc), N=N_cal, pls.cal)
cal.stats

################### Get model statistics #########################
mdstats<-bind_rows(cal.stats, val.stats)

#Create model stats labels for the plot
#FUSI EDIT: Removed comps from before N because plot was crowded should add back in and only remove in plot below 
slct.stats<-as.data.frame(t(mdstats[,c("Property","N","R2","RMSE","bias","RPIQ" )])) 
names(slct.stats)<-NULL
slct.stats<-bind_cols(rownames(slct.stats),slct.stats[,2])

#FUSI EDIT: added "comps" because it is in slct.stats 
valbls<-paste0(c("N","R2","RMSE","bias","RPIQ"), "\n")
valsts<-paste0(c(slct.stats[2,2],slct.stats[3,2],slct.stats[4,2],slct.stats[5,2],slct.stats[6,2]))
valstats<-paste(valbls,valsts)

#Bind all looped properties model stats
mdl.stats<-bind_rows(mdl.stats,mdstats)


lgth<-length(sort(dfval.f,decreasing=F))

seq.int(sort(dfval.f,decreasing=F)[1], sort(dfval.f,decreasing=F)[lgth],length.out=4)

#Plot validation plot
plot(dfval.f,pls.prd,pch=10,
     xlab=paste('Measured',names(val_df)[2],sep="_"),
     ylab=paste('Predicted',names(val_df)[2],sep="_"), 
     xlim = range(c(dfval.f,pls.prd)),
     ylim = range(c(dfval.f,pls.prd)),
     mtext(valstats[-1],side=3, at=c(seq.int(sort(dfval.f,decreasing=F)[1], sort(dfval.f,decreasing=F)[lgth],length.out=4)))
     )   ## plot the predicted vs. measured in the validation
abline(a = 0, b = 1)


dir.create("Plots_Validationplots_PLSR_MIR_Ash1")
png(paste0(getwd(),"/Plots_Validationplots_PLSR_MIR_Ash1/",slprptr[p],".png"))
print(plot(dfval.f,pls.prd,pch=10,
           xlab=paste('Measured',names(val_df)[2],sep="_"),
           ylab=paste('Predicted',names(val_df)[2],sep="_"), 
           xlim = range(c(dfval.f,pls.prd)),
           ylim = range(c(dfval.f,pls.prd)),
           mtext(valstats[-1],side=3, at=c(seq.int(sort(dfval.f,decreasing=F)[1], sort(dfval.f,decreasing=F)[lgth],length.out=4)))
           ))
abline(a = 0, b = 1)
dev.off()


################### Predict all samples #########################
prd.smpls <- predict(pls.md, spec_trt[,-1])

prd<-as.data.frame(prd.smpls)
df.prd<-bind_cols(SSN=rownames(prd),prd[,nc])
colnames(df.prd)<-c("SSN",slprptr[p])

pred<-merge(pred, df.prd, by="SSN", all.x = T)

  } else {
    print(paste("Skipping testing parameter:", slprptr[p], "because val_df is empty."))
  }

}
#FUSI EDIT: End of for loop

```

```{r}

# Add two new columns based on whether the Property contains "_val" or "_cal"
mdl.stats_PLSR_MIR_Ash1 <- mdl.stats %>%
  mutate(Property_Name = gsub("(_cal|_val).*", "", Property),
         Data_Type = ifelse(grepl("_val", Property), "_val", "_cal"))

#Write model statistics and predicted values to the local drive
write.csv(mdl.stats_PLSR_MIR_Ash1, paste0(getwd(),"/Model_Statistics_PLSR_MIR_Ash1.csv"),row.names = F)
write.csv(pred, paste0(getwd(),"/Predicted_Biochar_Properties_PLSR_MIR_Ash1.csv"),row.names = F)

saveRDS(mdl.stats_PLSR_MIR_Ash1,"mdl.stats_PLSR_MIR_Ash1.RDS")
```

```{r}

mdl.stats_PLSR_MIR_Ash1 <- readRDS("mdl.stats_PLSR_MIR_Ash1.RDS")

# Filter out rows with missing R2 values
mdl.stats_filtered <- mdl.stats_PLSR_MIR_Ash1[complete.cases(mdl.stats_PLSR_MIR_Ash1$R2), ]

# Order the properties based on R2 values in descending order for _cal data
ordered_props_cal <- mdl.stats_filtered[mdl.stats_filtered$Data_Type == "_cal", ]
ordered_props_cal <- ordered_props_cal[order(-ordered_props_cal$R2), "Property_Name"]
top_properties_cal <- head(ordered_props_cal, 10)

# Filter the original dataframe for the selected top properties and both _cal and _val data
mdl.stats_top <- mdl.stats_filtered[mdl.stats_filtered$Property_Name %in% top_properties_cal, ]

# Create a new factor variable to control the order of bars
mdl.stats_top$Property_Name <- factor(mdl.stats_top$Property_Name, levels = top_properties_cal)

# Plotting
cal_val_top_plot <- ggplot(mdl.stats_top, aes(x = Property_Name, y = R2, fill = Data_Type, group = Data_Type)) +
  geom_bar(stat = "identity", position = position_dodge(width = 0.8), width = 0.7) +
  labs(title = "Top Properties with Highest R2 for PLSR MIR Ash1",
       x = "Property",
       y = "R2") +
  theme_minimal()

# Save the plot
ggsave(paste0(getwd(), "/cal_val_PLSR_MIR_Ash1", ".png"),
       plot = cal_val_top_plot,
       width = 8,
       height = 6, 
       units = "in",
       dpi = 300)


```

## Correlation Matrices

help from the following [link](http://www.sthda.com/english/wiki/correlation-matrix-a-quick-start-guide-to-analyze-format-and-visualize-a-correlation-matrix-using-r-software)

```{r, message=FALSE}
library(Hmisc)
library(PerformanceAnalytics)
library(gplots)
library(plotly)
```

### Hierrchical Clustering

```{r}
df.f$Temp.<-as.numeric(df.f$Temp.)
#df.f[,-1]<-as.numeric(unlist((df.f[,-1]))
cor_mat<-rcorr(as.matrix(df.f[,c(2:ncol(df.f))]))
cor_mat


#Hierrchical Clustering
cor_mat_data<-df.f[,2:(ncol(df.f)-2)]

cor_mat_2<-cor(cor_mat_data, use = "pairwise.complete.obs")
#calculates correlations pairwise between variables while excluding observations that have missing values in either of the two variables being correlated

Hierchical_cluster<-heatmap.2(cor_mat_2, 
          #col = colorRampPalette(c("blue", "white", "red"))(50), 
          dendrogram = "both",
          trace = "none",
          #margins = c(10, 10),
          main = "Correlation Heatmap")
Hierchical_cluster

```

### Interactive Heatmap

```{r}

heatmap_interactive <- plot_ly(
  x = colnames(cor_mat_2),
  y = colnames(cor_mat_2),
  z = cor_mat_2,
  type = "heatmap",
  colorscale = "Viridis"
)
heatmap_interactive

```

```{r}

filtered_cor_mat <- cor_mat_2
filtered_cor_mat[filtered_cor_mat > -0.75 & filtered_cor_mat <0.75] <- NA


#filtered_cor_mat[filtered_cor_mat < 0.75 | filtered_cor_mat > 0.99] <- NA

heatmap_interactive_2 <- plot_ly(
  x = colnames(filtered_cor_mat),
  y = colnames(filtered_cor_mat),
  z = filtered_cor_mat,
  type = "heatmap",
  colorscale = "Viridis"
)
heatmap_interactive_2
```

```{r}

df <- data.frame(
  A = c(1, 2, NA, 4),
  B = c(NA, 2, 3, 4)
)

# Remove rows containing NA values
df_clean <- df[complete.cases(df), ]
```

```{r, warning=FALSE}

corr_data<-df.f[,c(2:20)]
chart.Correlation(corr_data)#, histogram=TRUE)
```

```{r, warning=FALSE}

corr_data_1<-df.f[,c(21:40)]
chart.Correlation(corr_data_1)#, histogram=TRUE)
```

```{r, warning=FALSE}

corr_data_2<-df.f[,c(41:ncol(df.f)-2)]
chart.Correlation(corr_data_2)#, histogram=TRUE)
```
