---
title: "CEBUM_Biochar_Factors"
output: html_document
date: "2024-02-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r, message=FALSE}
library(ggbiplot)
library(RColorBrewer)
library(viridis)
library(dplyr)
```

### Grouping Reference Data and Plotting for All Characteristics

```{r}


# Function to segment data and create plot for each column
create_plots <- function(col_name, df) {
  # Copy the original column to ensure the original data is preserved
  col_numeric <- df[[col_name]]
  
  # Convert the column to numeric, handling NAs
  col_numeric <- as.numeric(as.character(col_numeric))
  col_numeric[is.na(df[[col_name]])] <- NA
  
  # Determine breaks automatically
  
  # if I want equal interval breaks
  # breaks <- pretty(col_numeric, n = 4)
  breaks <- quantile(df.f[[col_name]], probs = seq(0, 1, by = 1/4), na.rm = TRUE)
  
   # Check if breaks are unique
  if (length(unique(breaks)) != length(breaks)) {
    # If breaks are not unique, use 'pretty' option
    breaks <- pretty(df.f[[col_name]][!is.na(df.f[[col_name]])], n = 4)
  }
  
  
  # Segment the data into equal intervals
  df_factors <- df %>%
    mutate(!!paste0(col_name, "_Factor") := cut(col_numeric, breaks = breaks, labels = paste0(breaks[-length(breaks)], "-", breaks[-1])))
  
  # Merge with spectral data
  spec_ref1 <- merge(df_factors, spec_trt)
  
  # Remove the ref data for the PCA
  x <- as.numeric(ncol(df_factors))
  pcs1 <- prcomp(spec_ref1[,-c(1:(x+2))])
  
  # Plot the data
  g1 <- ggbiplot(pcs1,
                 obs.scale = 1,
                 var.scale = 1,
                 groups = spec_ref1[[paste0(col_name, "_Factor")]],
                 var.axes = FALSE) +
    labs(title = paste("PCA plot with", col_name, "for column", col_name)) +
    theme_minimal() +
    theme(panel.border = element_rect(color = "black",
                                      fill = NA,
                                      size = 2),
          plot.title = element_text(hjust = 0.5)) +
    guides(color = guide_legend(paste0(col_name, " Range")))
  
  return(g1)
}

#Recall df.f
df.f<-readRDS("df.f.RDS")
spec_trt <- readRDS("spec_trt_MIR.RDS")

# Get column names except the first few which are ID and metadata
df_columns <- names(df.f)[-c(1:9)]

# Create plots for each column
plots_list <- lapply(df_columns, create_plots, df = df.f)

# Print all plots
for (i in seq_along(plots_list)) {
  print(plots_list[[i]])
}


```

### Manually Grouping Reference Data

Grouping reference data by temperature

```{r}

#Recalling df.f since it's been overidden
df.f<-readRDS("df.f.RDS")
spec_trt <- readRDS("spec_trt_MIR.RDS")

#converting class to factor

df.f$Class <- as.factor(df.f$Class)

df.f<-df.f %>%
  dplyr::mutate(Temp_factor = case_when(Temp.>=200 & Temp.<400 ~ 1,
                                        Temp.>=400 & Temp.<=550 ~ 2,
                                  Temp.>550 & Temp.<1000 ~ 3))


df.f$Temp_factor<-as.factor(df.f$Temp_factor)
##

df.f<-df.f %>%
  dplyr::mutate(H_C_factor = case_when(Htot_to_Ctot_.molar.>=0 & Htot_to_Ctot_.molar.<=1.25 ~ 1,
                                       Htot_to_Ctot_.molar.>1.25 & Htot_to_Ctot_.molar.<=2.0 ~ 2))

df.f<-df.f %>%
  dplyr::mutate(Ash_factor = case_when(Ash_avg>=0 & Ash_avg<=0.45 ~ 1,
                                       Ash_avg>0.45 & Ash_avg<=1.0 ~ 2))

df.f<-df.f %>%
  dplyr::mutate(O_C_factor = case_when(Oult_to_Ctot_.molar.>=0 & Oult_to_Ctot_.molar.<=0.25 ~ 1,
  
                                       Oult_to_Ctot_.molar.>=0.25 & Oult_to_Ctot_.molar.<=0.45 ~ 2,
                                       Oult_to_Ctot_.molar.>0.45 & Oult_to_Ctot_.molar.<=1.5 ~ 3))


df.f$Temp_factor<-as.factor(df.f$Temp_factor)
df.f$H_C_factor<-as.factor(df.f$H_C_factor)
df.f$Ash_factor<-as.factor(df.f$Ash_factor)
df.f$O_C_factor<-as.factor(df.f$O_C_factor)
df.f$Temp.<-as.numeric(df.f$Temp.)
#Need to consider including NA as a level (mutate doesn't do it)

df.f_split_Temp<-split(df.f,df.f$Temp_factor)
df.f_split_H_C<-split(df.f,df.f$H_C_factor)
df.f_split_Ash<-split(df.f,df.f$Ash_factor)
df.f_split_O_C<-split(df.f,df.f$O_C_factor)

df_f_H_C_1<-df.f_split_H_C[["1"]]
df_f_H_C_2<-df.f_split_H_C[["2"]]

df_f_Ash_1<-df.f_split_Ash[["1"]]
df_f_Ash_2<-df.f_split_Ash[["2"]]

saveRDS(df_f_Ash_1,"df_f_Ash_1.RDS")
saveRDS(df_f_Ash_2,"df_f_Ash_2.RDS")
saveRDS(df_f_H_C_1,"df_f_H_C_1.RDS")
saveRDS(df_f_H_C_2,"df_f_H_C_2.RDS")
```

```{r}


saveRDS(df.f,"df_f_factors.RDS")


```

## PCA with Reference Data for Grouping

```{r}

 #Merging spectral (spec_trt) used for PCA earlier with ref data (df.f)

#removed samples with Temp = 950 

spec_ref1 <- merge(df.f,spec_trt)

spec_refA<-spec_ref1%>% filter(is.na(Temp.)|Temp.!=950)


#removing the ref data for the PCA
x<-as.numeric(ncol(df.f))

pcs1 <- prcomp(spec_refA[,-c(1:(x+1))]) # removing the first row of the spec data because its NA's
               
#?extracting the first 10 components?

pcss1 <- pcs1$x[,1:10]

pcss1[1:6,]

plot(pcss1)

```

### PCA with Class Factor

```{r}

g <- ggbiplot::ggbiplot(pcs1,
                        obs.scale = 1,
                        var.scale = 1 ,
                        groups = spec_refA$Class,
                        var.axes = FALSE)

g <- g + scale_color_brewer(palette = "Set1", name = "Biochar Class") + 
  theme_minimal() +
  theme(panel.grid = element_blank(),  # Remove grid
        panel.border = element_rect(color = "black", fill = NA, size = 2),
        plot.title = element_text(hjust = 0.5))

g 
```

### PCA with Feedstock Factor

```{r}

# Custom color palette with 20 distinct colors
custom_palette <- colorRampPalette(brewer.pal(8, "Set1"))(30)

g <- ggbiplot::ggbiplot(pcs1,
                        obs.scale = 1,
                        var.scale = 1,
                        groups = spec_refA$Feedstock,
                        var.axes = FALSE)

g <- g + scale_color_manual(values = custom_palette, name = "Biochar Feedstock") +
    theme_minimal() +
  theme(panel.grid = element_blank(),  # Remove grid
        panel.border = element_rect(color = "black", fill = NA, size = 2),
        plot.title = element_text(hjust = 0.5))

g 
```

### PCA with Temperature Factor

```{r}

g1 <- ggbiplot::ggbiplot(pcs1, #need to specify which library the command is coming from, gives errors otherwise
              obs.scale = 1,
              var.scale = 1 ,
              groups = spec_refA$Temp_factor,
              #ellipse = TRUE,
              #circle = TRUE,
              #ellipse.prob = 0.68,
              var.axes=FALSE) 

g1<- g1 + labs(title = "PCA plot with Temp Factor") +
  theme_minimal() + 
  #theme_void() +  # This removes both grid and background
  theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 2),
                                    plot.title = element_text(hjust = 0.5))+
  guides(color=guide_legend("Temperature Range (C)")) + 
  scale_color_manual(labels = c("200-400","400-550","550+","NA"), values=c("brown","red","orange","green")) 
g1
```

### PCA with H:C Factor

```{r}

plot_pca_HC <- ggbiplot::ggbiplot(pcs1, #need to specify which library the command is coming from, gives errors otherwise
              obs.scale = 1,
              var.scale = 1 ,
              groups = spec_refA$H_C_factor,
              #ellipse = TRUE,
              ##circle = TRUE,
              #ellipse.prob = 0.68,
              var.axes=FALSE) 


plot_pca_HC<- plot_pca_HC + labs(title = "PCA plot with HC Factor") +
  theme_minimal() +
  theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 2),
                                    plot.title = element_text(hjust = 0.5))+
  guides(color=guide_legend("H:C Range")) + 
  scale_color_manual(labels = c("0-1.25",">1.25"), values=c("orange","green")) 
plot_pca_HC
```

### PCA with Ash Factor

```{r}

plot_pca_Ash <- ggbiplot::ggbiplot(pcs1, #need to specify which library the command is coming from, gives errors otherwise
              obs.scale = 1,
              var.scale = 1 ,
              groups = spec_refA$Ash_factor,
              #ellipse = TRUE,
              ##circle = TRUE,
              #ellipse.prob = 0.68,
              var.axes=FALSE) 


plot_pca_Ash<- plot_pca_Ash + labs(title = "PCA plot with Ash Factor") +
  theme_minimal() +
  theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 2),
                                    plot.title = element_text(hjust = 0.5))+
  guides(color=guide_legend("Ash Range")) + 
  scale_color_manual(labels = c("0-0.45","0.45-1"), values=c("purple","gold")) 
plot_pca_Ash
```

### PCA with O:C Factor

```{r}

plot_pca_O_C <- ggbiplot::ggbiplot(pcs1, #need to specify which library the command is coming from, gives errors otherwise
              obs.scale = 1,
              var.scale = 1 ,
              groups = spec_refA$O_C_factor,
              #ellipse = TRUE,
              ##circle = TRUE,
              #ellipse.prob = 0.68,
              var.axes=FALSE)

plot_pca_O_C <- plot_pca_O_C  + labs(title = "PCA plot with O:C Factor") +
  theme_minimal() +
  theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 2),
                                    plot.title = element_text(hjust = 0.5))+
  guides(color=guide_legend("O:C Range")) + 
  scale_color_manual(labels = c("0-0.15","0.15-0.45",">0.45"), values=c("peru","pink","green")) 
plot_pca_O_C
```
